[Behavior]
hideDockIcon=false
hideMainWindowWhenStarted=false

[MainWindow]
pos=@Point(3845 26)
size=@Size(1910 1049)

[RepoTreeView]
expandedCategories-676b1f6=Recently Updated

[Settings]
computerName=archlinux

[UsedServerAddresses]
main=https://seafile.coeus.icu
