github.com:
    users:
        bigdale123:
            oauth_token: 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
    git_protocol: https
    user: bigdale123
    oauth_token: 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
