[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\v/home/dylan)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\vB\0\0\0\x1a\0\0\xe\xfa\0\0\x4\x32\0\0\vC\0\0\0\x1b\0\0\xe\xf9\0\0\x4\x31\0\0\0\x1\0\0\0\0\a\x80\0\0\vC\0\0\0\x1b\0\0\xe\xf9\0\0\x4\x31)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(600 0)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/dylan/Downloads/Tradition_-_Bock__Harnick_Fiddler_On_The_Roof_Musical_Piano-Vocal-Guitar.mp3, file:///home/dylan/.config/sdrpp/recordings/audio_128725000Hz_20-31-40_28-04-2024.wav, file:///home/dylan/.config/sdrpp/recordings/audio_127300000Hz_19-57-45_28-04-2024.wav, file:///home/dylan/.config/sdrpp/recordings/audio_127300000Hz_19-58-23_28-04-2024.wav, file:///home/dylan/.config/sdrpp/recordings/audio_128725000Hz_20-00-47_28-04-2024.wav, file:///home/dylan/.config/sdrpp/recordings/audio_126825000Hz_20-18-57_28-04-2024.wav
times=16976, 0, 0, 0, 0, 0
