wallpaper {
    monitor = desc:ViewSonic Corporation VA2465 SERIES U9D164243089
    path = ~/.config/wallpapers/hoover_midnight_blue_vertical.png
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/.config/wallpapers/hoover_midnight_blue_horizontal.png
    fit_mode = cover
}
