-- Generated by nwg-displays on 2026-08-12 at 09:31:18. Do not edit manually.

hl.monitor({
    output = "desc:Lenovo Group Limited 0x40A9",
    mode = "1920x1080@60.02",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "desc:ViewSonic Corporation VA2465 SERIES U9D164243089",
    mode = "1920x1080@60.0",
    position = "3840x0",
    scale = 1.0
})
hl.monitor({
    output = "desc:ASUSTek COMPUTER INC ASUS VG328 0x00000E44",
    mode = "1920x1080@74.99",
    position = "1920x0",
    scale = 1.0
})
